# security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Membre
                property: username # Ou le nom de la propriété utilisée comme nom d'utilisateur
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_home # Ou l'URL vers laquelle rediriger après la déconnexion
            # ... autres configurations ...
    access_control:
        # ... autres configurations ...
