when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error


home:
    path: /
    controller: App\Controller\HomeController::index

connexion:
    path: /connexion
    controller: App\Controller\SecurityController::index
